version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2022
build_script:
- cmd: >-
    mkdir build

    cd build

    cmake .. -A Win32

    cmake --build . --config Release
artifacts:
- path: .\out\install\Release\d2_item_mover.dll
  name: d2_item_mover_v${APPVEYOR_BUILD_VERSION}
  type: WebDeployPackage
deploy:
- provider: Environment
  name: Github
  on:
    branch: Master